// Generated by make_mock_data.py. Do not edit by hand.
window.DEMO = {
  "index": {
    "sequences": [
      {
        "id": "clear_growing_fire",
        "display_name": "Clear growing fire",
        "case": "clear_growing_fire",
        "models": [
          {
            "id": "molmo2-8b",
            "label": "Molmo 2 (8B)",
            "family": "VLM"
          },
          {
            "id": "molmo2-4b",
            "label": "Molmo 2 (4B)",
            "family": "VLM"
          }
        ],
        "n_frames": 10
      },
      {
        "id": "small_edge_fire",
        "display_name": "Small fire at frame edge",
        "case": "small_edge_fire",
        "models": [
          {
            "id": "molmo2-8b",
            "label": "Molmo 2 (8B)",
            "family": "VLM"
          },
          {
            "id": "molmo2-4b",
            "label": "Molmo 2 (4B)",
            "family": "VLM"
          }
        ],
        "n_frames": 10
      },
      {
        "id": "smoke_obscured",
        "display_name": "Smoke-obscured fire",
        "case": "smoke_obscured",
        "models": [
          {
            "id": "molmo2-8b",
            "label": "Molmo 2 (8B)",
            "family": "VLM"
          },
          {
            "id": "molmo2-4b",
            "label": "Molmo 2 (4B)",
            "family": "VLM"
          }
        ],
        "n_frames": 10
      },
      {
        "id": "no_fire",
        "display_name": "No fire",
        "case": "no_fire",
        "models": [
          {
            "id": "molmo2-8b",
            "label": "Molmo 2 (8B)",
            "family": "VLM"
          },
          {
            "id": "molmo2-4b",
            "label": "Molmo 2 (4B)",
            "family": "VLM"
          }
        ],
        "n_frames": 8
      }
    ]
  },
  "sequences": {
    "clear_growing_fire": {
      "sequence_id": "clear_growing_fire",
      "display_name": "Clear growing fire",
      "case": "clear_growing_fire",
      "source": {
        "dataset": "FLAME3",
        "flight": "Sycan Marsh, Oct 27 PM",
        "has_thermal": true,
        "frame_interval_sec": 60,
        "pose_stable": true,
        "gsd_m_per_px": null
      },
      "frames": [
        {
          "index": 0,
          "t_sec": 0,
          "clock": "13:02:00",
          "detection_score": 0.94,
          "fire": true,
          "radius_frac": 0.04,
          "radius_m": null,
          "centroid": [
            0.56,
            0.63
          ],
          "overlay_png": null
        },
        {
          "index": 1,
          "t_sec": 60,
          "clock": "13:03:00",
          "detection_score": 0.95,
          "fire": true,
          "radius_frac": 0.06,
          "radius_m": null,
          "centroid": [
            0.574,
            0.578
          ],
          "overlay_png": null
        },
        {
          "index": 2,
          "t_sec": 120,
          "clock": "13:04:00",
          "detection_score": 0.96,
          "fire": true,
          "radius_frac": 0.08,
          "radius_m": null,
          "centroid": [
            0.554,
            0.552
          ],
          "overlay_png": null
        },
        {
          "index": 3,
          "t_sec": 180,
          "clock": "13:05:00",
          "detection_score": 0.97,
          "fire": true,
          "radius_frac": 0.1,
          "radius_m": null,
          "centroid": [
            0.5,
            0.553
          ],
          "overlay_png": null
        },
        {
          "index": 4,
          "t_sec": 240,
          "clock": "13:06:00",
          "detection_score": 0.97,
          "fire": true,
          "radius_frac": 0.13,
          "radius_m": null,
          "centroid": [
            0.446,
            0.554
          ],
          "overlay_png": null
        },
        {
          "index": 5,
          "t_sec": 300,
          "clock": "13:07:00",
          "detection_score": 0.98,
          "fire": true,
          "radius_frac": 0.16,
          "radius_m": null,
          "centroid": [
            0.426,
            0.529
          ],
          "overlay_png": null
        },
        {
          "index": 6,
          "t_sec": 360,
          "clock": "13:08:00",
          "detection_score": 0.98,
          "fire": true,
          "radius_frac": 0.19,
          "radius_m": null,
          "centroid": [
            0.44,
            0.477
          ],
          "overlay_png": null
        },
        {
          "index": 7,
          "t_sec": 420,
          "clock": "13:09:00",
          "detection_score": 0.99,
          "fire": true,
          "radius_frac": 0.22,
          "radius_m": null,
          "centroid": [
            0.454,
            0.424
          ],
          "overlay_png": null
        },
        {
          "index": 8,
          "t_sec": 480,
          "clock": "13:10:00",
          "detection_score": 0.99,
          "fire": true,
          "radius_frac": 0.25,
          "radius_m": null,
          "centroid": [
            0.434,
            0.399
          ],
          "overlay_png": null
        },
        {
          "index": 9,
          "t_sec": 540,
          "clock": "13:11:00",
          "detection_score": 0.99,
          "fire": true,
          "radius_frac": 0.28,
          "radius_m": null,
          "centroid": [
            0.38,
            0.4
          ],
          "overlay_png": null
        }
      ],
      "thermal_reference": {
        "available": true,
        "fire_present": true,
        "trend": "growing",
        "direction": "toward upper left of frame",
        "angle_deg": 322
      },
      "default_model": "molmo2-8b",
      "models": {
        "molmo2-8b": {
          "label": "Molmo 2 (8B)",
          "family": "VLM",
          "brief": {
            "presence": "Fire confirmed, open flame with active spread",
            "extent": "Radius grew from about 4% to 28% of the frame over 9 minutes",
            "direction": {
              "value": "toward upper left of frame",
              "frame_relative": true,
              "compass": null,
              "angle_deg": 318
            },
            "trend": "growing",
            "confidence": "high",
            "limitations": [
              "Heading not logged, so direction is frame-relative, not a compass bearing"
            ]
          },
          "agreement": {
            "presence": true,
            "trend": true,
            "direction": true
          },
          "size_estimate_frac": 0.26
        },
        "molmo2-4b": {
          "label": "Molmo 2 (4B)",
          "family": "VLM",
          "brief": {
            "presence": "Fire confirmed with active spread",
            "extent": "Expanding, roughly a quarter of the frame by the end",
            "direction": {
              "value": "toward top of frame",
              "frame_relative": true,
              "compass": null,
              "angle_deg": 352
            },
            "trend": "growing",
            "confidence": "medium",
            "limitations": [
              "Called the spread direction as upward; thermal centroid drifts more to the left"
            ]
          },
          "agreement": {
            "presence": true,
            "trend": true,
            "direction": false
          },
          "size_estimate_frac": 0.18
        }
      }
    },
    "small_edge_fire": {
      "sequence_id": "small_edge_fire",
      "display_name": "Small fire at frame edge",
      "case": "small_edge_fire",
      "source": {
        "dataset": "FLAME3",
        "flight": "Sycan Marsh, Oct 27 AM",
        "has_thermal": true,
        "frame_interval_sec": 60,
        "pose_stable": true,
        "gsd_m_per_px": null
      },
      "frames": [
        {
          "index": 0,
          "t_sec": 0,
          "clock": "13:02:00",
          "detection_score": 0.54,
          "fire": true,
          "radius_frac": 0.03,
          "radius_m": null,
          "centroid": [
            0.9,
            0.47
          ],
          "overlay_png": null
        },
        {
          "index": 1,
          "t_sec": 60,
          "clock": "13:03:00",
          "detection_score": 0.58,
          "fire": true,
          "radius_frac": 0.032,
          "radius_m": null,
          "centroid": [
            0.888,
            0.472
          ],
          "overlay_png": null
        },
        {
          "index": 2,
          "t_sec": 120,
          "clock": "13:04:00",
          "detection_score": 0.52,
          "fire": true,
          "radius_frac": 0.03,
          "radius_m": null,
          "centroid": [
            0.896,
            0.474
          ],
          "overlay_png": null
        },
        {
          "index": 3,
          "t_sec": 180,
          "clock": "13:05:00",
          "detection_score": 0.61,
          "fire": true,
          "radius_frac": 0.035,
          "radius_m": null,
          "centroid": [
            0.91,
            0.477
          ],
          "overlay_png": null
        },
        {
          "index": 4,
          "t_sec": 240,
          "clock": "13:06:00",
          "detection_score": 0.57,
          "fire": true,
          "radius_frac": 0.033,
          "radius_m": null,
          "centroid": [
            0.908,
            0.479
          ],
          "overlay_png": null
        },
        {
          "index": 5,
          "t_sec": 300,
          "clock": "13:07:00",
          "detection_score": 0.63,
          "fire": true,
          "radius_frac": 0.036,
          "radius_m": null,
          "centroid": [
            0.892,
            0.481
          ],
          "overlay_png": null
        },
        {
          "index": 6,
          "t_sec": 360,
          "clock": "13:08:00",
          "detection_score": 0.55,
          "fire": true,
          "radius_frac": 0.034,
          "radius_m": null,
          "centroid": [
            0.89,
            0.483
          ],
          "overlay_png": null
        },
        {
          "index": 7,
          "t_sec": 420,
          "clock": "13:09:00",
          "detection_score": 0.6,
          "fire": true,
          "radius_frac": 0.037,
          "radius_m": null,
          "centroid": [
            0.904,
            0.486
          ],
          "overlay_png": null
        },
        {
          "index": 8,
          "t_sec": 480,
          "clock": "13:10:00",
          "detection_score": 0.58,
          "fire": true,
          "radius_frac": 0.035,
          "radius_m": null,
          "centroid": [
            0.912,
            0.488
          ],
          "overlay_png": null
        },
        {
          "index": 9,
          "t_sec": 540,
          "clock": "13:11:00",
          "detection_score": 0.62,
          "fire": true,
          "radius_frac": 0.038,
          "radius_m": null,
          "centroid": [
            0.9,
            0.49
          ],
          "overlay_png": null
        }
      ],
      "thermal_reference": {
        "available": true,
        "fire_present": true,
        "trend": "stable",
        "direction": "indeterminate",
        "angle_deg": null
      },
      "default_model": "molmo2-8b",
      "models": {
        "molmo2-8b": {
          "label": "Molmo 2 (8B)",
          "family": "VLM",
          "brief": {
            "presence": "Small hotspot confirmed near the right edge",
            "extent": "Under 4% of the frame throughout",
            "direction": {
              "value": "indeterminate",
              "frame_relative": true,
              "compass": null,
              "angle_deg": null
            },
            "trend": "stable",
            "confidence": "medium",
            "limitations": [
              "Hotspot sits at the frame edge and may be partially out of view",
              "Detection score stays near the threshold, so a missed frame is plausible"
            ]
          },
          "agreement": {
            "presence": true,
            "trend": true,
            "direction": true
          },
          "size_estimate_frac": 0.04
        },
        "molmo2-4b": {
          "label": "Molmo 2 (4B)",
          "family": "VLM",
          "brief": {
            "presence": "Growing fire on the right side",
            "extent": "Small but increasing",
            "direction": {
              "value": "toward the right of frame",
              "frame_relative": true,
              "compass": null,
              "angle_deg": 90
            },
            "trend": "growing",
            "confidence": "low",
            "limitations": [
              "Read the frame-to-frame score noise as real growth"
            ]
          },
          "agreement": {
            "presence": true,
            "trend": false,
            "direction": false
          },
          "size_estimate_frac": 0.07
        }
      }
    },
    "smoke_obscured": {
      "sequence_id": "smoke_obscured",
      "display_name": "Smoke-obscured fire",
      "case": "smoke_obscured",
      "source": {
        "dataset": "FLAME3",
        "flight": "Sycan Marsh, Oct 27 PM",
        "has_thermal": true,
        "frame_interval_sec": 60,
        "pose_stable": true,
        "gsd_m_per_px": null
      },
      "frames": [
        {
          "index": 0,
          "t_sec": 0,
          "clock": "13:02:00",
          "detection_score": 0.82,
          "fire": true,
          "radius_frac": 0.06,
          "radius_m": null,
          "centroid": [
            0.48,
            0.55
          ],
          "overlay_png": null
        },
        {
          "index": 1,
          "t_sec": 60,
          "clock": "13:03:00",
          "detection_score": 0.86,
          "fire": true,
          "radius_frac": 0.07,
          "radius_m": null,
          "centroid": [
            0.465,
            0.606
          ],
          "overlay_png": null
        },
        {
          "index": 2,
          "t_sec": 120,
          "clock": "13:04:00",
          "detection_score": 0.71,
          "fire": true,
          "radius_frac": 0.08,
          "radius_m": null,
          "centroid": [
            0.487,
            0.599
          ],
          "overlay_png": null
        },
        {
          "index": 3,
          "t_sec": 180,
          "clock": "13:05:00",
          "detection_score": 0.63,
          "fire": true,
          "radius_frac": 0.075,
          "radius_m": null,
          "centroid": [
            0.535,
            0.547
          ],
          "overlay_png": null
        },
        {
          "index": 4,
          "t_sec": 240,
          "clock": "13:06:00",
          "detection_score": 0.49,
          "fire": false,
          "radius_frac": 0.09,
          "radius_m": null,
          "centroid": [
            0.563,
            0.53
          ],
          "overlay_png": null
        },
        {
          "index": 5,
          "t_sec": 300,
          "clock": "13:07:00",
          "detection_score": 0.55,
          "fire": true,
          "radius_frac": 0.085,
          "radius_m": null,
          "centroid": [
            0.552,
            0.58
          ],
          "overlay_png": null
        },
        {
          "index": 6,
          "t_sec": 360,
          "clock": "13:08:00",
          "detection_score": 0.46,
          "fire": false,
          "radius_frac": 0.095,
          "radius_m": null,
          "centroid": [
            0.534,
            0.642
          ],
          "overlay_png": null
        },
        {
          "index": 7,
          "t_sec": 420,
          "clock": "13:09:00",
          "detection_score": 0.52,
          "fire": true,
          "radius_frac": 0.09,
          "radius_m": null,
          "centroid": [
            0.55,
            0.644
          ],
          "overlay_png": null
        },
        {
          "index": 8,
          "t_sec": 480,
          "clock": "13:10:00",
          "detection_score": 0.44,
          "fire": false,
          "radius_frac": 0.1,
          "radius_m": null,
          "centroid": [
            0.597,
            0.594
          ],
          "overlay_png": null
        },
        {
          "index": 9,
          "t_sec": 540,
          "clock": "13:11:00",
          "detection_score": 0.5,
          "fire": true,
          "radius_frac": 0.095,
          "radius_m": null,
          "centroid": [
            0.63,
            0.568
          ],
          "overlay_png": null
        }
      ],
      "thermal_reference": {
        "available": true,
        "fire_present": true,
        "trend": "growing",
        "direction": "toward lower right of frame",
        "angle_deg": 135
      },
      "default_model": "molmo2-8b",
      "models": {
        "molmo2-8b": {
          "label": "Molmo 2 (8B)",
          "family": "VLM",
          "brief": {
            "presence": "Fire present but obscured by dense smoke in RGB",
            "extent": "Not reliably measurable from RGB after frame 4",
            "direction": {
              "value": "indeterminate",
              "frame_relative": true,
              "compass": null,
              "angle_deg": null
            },
            "trend": "indeterminate",
            "confidence": "low",
            "limitations": [
              "Dense smoke obscures the fire in RGB from frame 4 onward",
              "Deferring trend and direction to the thermal reference"
            ]
          },
          "agreement": {
            "presence": true,
            "trend": false,
            "direction": false
          },
          "size_estimate_frac": null
        },
        "molmo2-4b": {
          "label": "Molmo 2 (4B)",
          "family": "VLM",
          "brief": {
            "presence": "Fire appears to be dying down",
            "extent": "Shrinking behind the smoke",
            "direction": {
              "value": "toward upper left of frame",
              "frame_relative": true,
              "compass": null,
              "angle_deg": 312
            },
            "trend": "receding",
            "confidence": "low",
            "limitations": [
              "Read the smoke plume as a shrinking fire; contradicted by thermal"
            ]
          },
          "agreement": {
            "presence": true,
            "trend": false,
            "direction": false
          },
          "size_estimate_frac": 0.05
        }
      }
    },
    "no_fire": {
      "sequence_id": "no_fire",
      "display_name": "No fire",
      "case": "no_fire",
      "source": {
        "dataset": "FLAME3",
        "flight": "Sycan Marsh, Oct 27 AM",
        "has_thermal": true,
        "frame_interval_sec": 60,
        "pose_stable": true,
        "gsd_m_per_px": null
      },
      "frames": [
        {
          "index": 0,
          "t_sec": 0,
          "clock": "13:02:00",
          "detection_score": 0.05,
          "fire": false,
          "radius_frac": 0.0,
          "radius_m": null,
          "centroid": null,
          "overlay_png": null
        },
        {
          "index": 1,
          "t_sec": 60,
          "clock": "13:03:00",
          "detection_score": 0.04,
          "fire": false,
          "radius_frac": 0.0,
          "radius_m": null,
          "centroid": null,
          "overlay_png": null
        },
        {
          "index": 2,
          "t_sec": 120,
          "clock": "13:04:00",
          "detection_score": 0.07,
          "fire": false,
          "radius_frac": 0.0,
          "radius_m": null,
          "centroid": null,
          "overlay_png": null
        },
        {
          "index": 3,
          "t_sec": 180,
          "clock": "13:05:00",
          "detection_score": 0.03,
          "fire": false,
          "radius_frac": 0.0,
          "radius_m": null,
          "centroid": null,
          "overlay_png": null
        },
        {
          "index": 4,
          "t_sec": 240,
          "clock": "13:06:00",
          "detection_score": 0.06,
          "fire": false,
          "radius_frac": 0.0,
          "radius_m": null,
          "centroid": null,
          "overlay_png": null
        },
        {
          "index": 5,
          "t_sec": 300,
          "clock": "13:07:00",
          "detection_score": 0.05,
          "fire": false,
          "radius_frac": 0.0,
          "radius_m": null,
          "centroid": null,
          "overlay_png": null
        },
        {
          "index": 6,
          "t_sec": 360,
          "clock": "13:08:00",
          "detection_score": 0.08,
          "fire": false,
          "radius_frac": 0.0,
          "radius_m": null,
          "centroid": null,
          "overlay_png": null
        },
        {
          "index": 7,
          "t_sec": 420,
          "clock": "13:09:00",
          "detection_score": 0.04,
          "fire": false,
          "radius_frac": 0.0,
          "radius_m": null,
          "centroid": null,
          "overlay_png": null
        }
      ],
      "thermal_reference": {
        "available": true,
        "fire_present": false,
        "trend": "not applicable",
        "direction": "not applicable",
        "angle_deg": null
      },
      "default_model": "molmo2-8b",
      "models": {
        "molmo2-8b": {
          "label": "Molmo 2 (8B)",
          "family": "VLM",
          "brief": {
            "presence": "No fire or smoke detected",
            "extent": "Not applicable",
            "direction": {
              "value": "not applicable",
              "frame_relative": true,
              "compass": null,
              "angle_deg": null
            },
            "trend": "not applicable",
            "confidence": "high",
            "limitations": [
              "Clear scene, no thermal signature above the 80 C threshold"
            ]
          },
          "agreement": {
            "presence": true,
            "trend": true,
            "direction": true
          },
          "size_estimate_frac": null
        },
        "molmo2-4b": {
          "label": "Molmo 2 (4B)",
          "family": "VLM",
          "brief": {
            "presence": "No fire or smoke detected",
            "extent": "Not applicable",
            "direction": {
              "value": "not applicable",
              "frame_relative": true,
              "compass": null,
              "angle_deg": null
            },
            "trend": "not applicable",
            "confidence": "high",
            "limitations": [
              "Clear scene, no thermal signature above the 80 C threshold"
            ]
          },
          "agreement": {
            "presence": true,
            "trend": true,
            "direction": true
          },
          "size_estimate_frac": null
        }
      }
    }
  }
};
